INSERT INTO TBL_STOCKS_GNLS_APPROVED (ticker, approve) VALUES ('AAPL','Y');
INSERT INTO TBL_STOCKS_GNLS_APPROVED (ticker, approve) VALUES ('GOOG','Y');
INSERT INTO TBL_STOCKS_GNLS_APPROVED (ticker, approve) VALUES ('AMZN','Y');
INSERT INTO TBL_STOCKS_GNLS_APPROVED (ticker, approve) VALUES ('NVDA', 'N');
INSERT INTO TBL_STOCKS_GNLS_APPROVED (ticker, approve) VALUES ('MSFT','Y');
INSERT INTO TBL_STOCKS_GNLS_APPROVED (ticker, approve) VALUES ('TSLA','Y');
INSERT INTO TBL_STOCKS_GNLS_APPROVED (ticker, approve) VALUES ('HOOD','Y');
INSERT INTO TBL_STOCKS_GNLS_APPROVED (ticker, approve) VALUES ('SQUA','Y');
INSERT INTO TBL_STOCKS_GNLS_APPROVED (ticker, approve) VALUES ('GBTC','Y');